Issue#16 切版＿熱門同學＆熱門股票&熱門回答
astrocamp/17th-BBForum pull request #84
Opened 2024-09-04 12:09 UTC by jenjiunsu

熱門股票應該長的畫面：
<img width="1513" alt="截圖 2024-09-04 20 08 50" src="https://github.com/user-attachments/assets/3b14f216-6af1-4b99-b25e-86bbc1c12702">

熱門同學應該長的畫面：
<img width="1513" alt="截圖 2024-09-04 20 07 58" src="https://github.com/user-attachments/assets/281b130d-9d25-4691-8b29-ac95e8130fd3">

熱門回答應該長的畫面：
<img width="1618" alt="截圖 2024-09-06 15 34 31" src="https://github.com/user-attachments/assets/49c33c14-d349-4fc9-91ab-0627a83b6cd5">

2024-09-05 01:40 UTC, emma0620 approved these changes

2024-09-05 02:11 UTC, cacachang requested changes

2024-09-05 02:11 UTC, cacachang commented on pages/urls.py
> +    path("member_profile/", views.member_profile, name="member_profile"),
為什麼這個是放在 pages 裡面的 urls

2024-09-05 02:11 UTC, cacachang commented on templates/pages/popular_students/popular_students_bar.html
> +                                    <div class="w-[50px] h-[50px] border-2 border-gray-300 rounded-full" style="background: url('https://fsv.cmoney.tw/cmstatic/head-icons/a53.gif'); background-size:
style 的東西可以放到 css 裡面

2024-09-05 02:11 UTC, cacachang commented on templates/pages/popular_students/popular_students_bar.html
> +                                    <div class="w-[50px] h-[50px] border-2 border-gray-300 rounded-full" style="background: url('https://fsv.cmoney.tw/cmstatic/head-icons/a53.gif'); background-size:
同上

2024-09-05 02:11 UTC, cacachang commented on templates/layouts/base.html
> +    {% if request.resolver_match.url_name != 'register' and request.resolver_match.url_name != 'sign_in' and request.resolver_match.url_name != 'auth_denied' and request.path == '/' or request.path =
用 templatetags 去把這個方法包起來

2024-09-05 02:11 UTC, cacachang commented on pages/views.py
> +    return render(req, "pages/popular_stocks/popular_stocks.html")
想一下他是不是應該要放在一個叫做 popular 的 app 裡面

2024-09-05 10:33 UTC, jenjiunsu commented on templates/pages/popular_students/popular_students_bar.html
> +                                    <div class="w-[50px] h-[50px] border-2 border-gray-300 rounded-full" style="background: url('https://fsv.cmoney.tw/cmstatic/head-icons/a53.gif'); background-size:
我已將popular資料夾內的所有html檔的style 東西，修改進css檔裡了，因此程式碼的可讀性應該會更高一些

2024-09-05 10:33 UTC, jenjiunsu commented on templates/pages/popular_students/popular_students_bar.html
> +                                    <div class="w-[50px] h-[50px] border-2 border-gray-300 rounded-full" style="background: url('https://fsv.cmoney.tw/cmstatic/head-icons/a53.gif'); background-size:
同上

2024-09-05 11:52 UTC, jenjiunsu commented on pages/views.py
> +    return render(req, "pages/popular_stocks/popular_stocks.html")
已新增：
<img width="437" alt="截圖 2024-09-05 19 52 23" src="https://github.com/user-attachments/assets/e478a7c7-8f96-40b6-ac3d-bdd221e887a3">

2024-09-06 01:58 UTC, cacachang commented on pages/views.py
> +    return render(req, "pages/popular_stocks/popular_stocks.html")
`pages` 應該可以放在 `templates` 底下，這樣就不用在 settings 裡面一直做設定

2024-09-06 06:46 UTC, jenjiunsu commented on pages/urls.py
> +    path("member_profile/", views.member_profile, name="member_profile"),
已更新：
<img width="1386" alt="截圖 2024-09-06 14 45 51" src="https://github.com/user-attachments/assets/a913b9c0-cbbc-47ef-9220-60cf6e5997d3">

2024-09-06 06:47 UTC, jenjiunsu commented on templates/layouts/base.html
> +    {% if request.resolver_match.url_name != 'register' and request.resolver_match.url_name != 'sign_in' and request.resolver_match.url_name != 'auth_denied' and request.path == '/' or request.path =
已包：
<img width="1386" alt="截圖 2024-09-06 14 46 58" src="https://github.com/user-attachments/assets/6c3e1cf1-215c-4b92-a82d-ca149292807d">

<img width="1386" alt="截圖 2024-09-06 14 47 42" src="https://github.com/user-attachments/assets/588cbdd7-28d1-44d7-b157-69e649b20b30">

2024-09-06 06:50 UTC, jenjiunsu commented on pages/views.py
> +    return render(req, "pages/popular_stocks/popular_stocks.html")
已放在 templates 底下：
<img width="384" alt="截圖 2024-09-06 14 48 39" src="https://github.com/user-attachments/assets/d4b8d9c3-2a2c-4c6d-9930-a213d93a2f36">

並已把 settings 清乾淨

2024-09-06 09:18 UTC, EricHsu521 commented
測試結果
目前三個畫面都正常
![image](https://github.com/user-attachments/assets/d2318b8e-8362-4f3b-9300-8bd6bc33ed43)
![image](https://github.com/user-attachments/assets/14c89e27-54cf-4c74-8002-6aeb5a7bc6ea)
![image](https://github.com/user-attachments/assets/021ec54a-8639-42df-91f2-10c13b24ab19)

需要修改的地方
點擊右上角Point的時候會壞掉
![image](https://github.com/user-attachments/assets/a3c75e0b-957e-4108-8e34-5b1a76a33fc8)

2024-09-07 07:42 UTC, EricHsu521 commented
測試結果
1. 畫面正常

需要修正問題，會員中心變成我的自選股然後轉跳到我的收藏
![image](https://github.com/user-attachments/assets/771d41df-4381-453c-92a7-e71ddc54379e)
![image](https://github.com/user-attachments/assets/5b6b678c-e0ef-45e5-8e6d-588433c7293f)

2024-09-07 08:37 UTC, EricHsu521 commented
測試ok

2024-09-07 08:38 UTC, EricHsu521 approved these changes

2024-09-07 09:36 UTC, emma0620 commented
測試畫面 ok
熱門股票
![image](https://github.com/user-attachments/assets/0de66a2d-6660-47a7-9c75-db44387e2e00)

熱門同學
![image](https://github.com/user-attachments/assets/99e2768f-d353-47c4-abc2-a4ba568a1708)

熱門回答
![image](https://github.com/user-attachments/assets/d92f5cb0-b90d-48e3-829c-f2a86a6d1a93)

2024-09-07 12:53 UTC, KANG0918 approved these changes

2024-09-07 13:24 UTC, LianSongYang approved these changes
測試ok

2024-09-07 13:24 UTC, merged