feat: 討論區 文章 分享超連結
astrocamp/17th-BBForum pull request #96
Opened 2024-09-08 05:59 UTC by emma0620

功能: 討論區 文章 分享超連結
測試:
1. 滑鼠指到 文章 "分享"  下方會出現複製連結, 按下去
![image](https://github.com/user-attachments/assets/d53f67f9-8de3-4233-9f69-b705adeeedf1)

2. 會出現 己複製
![image](https://github.com/user-attachments/assets/08d3a231-489a-4c60-9e75-849d8105f2ed)

3. 再貼到空白網頁的網址處, 執行, 會秀出 文章內文 (此頁待討論)
![image](https://github.com/user-attachments/assets/47176240-40c0-43d6-b5d9-94b8f24b925d)

2024-09-08 11:13 UTC, LianSongYang approved these changes
測試ok

2024-09-09 02:28 UTC, cacachang requested changes

2024-09-09 02:28 UTC, cacachang commented on templates/pages/main_page/_article.html
> +                                         @click="url = window.location.origin + '{% url 'articles:show' article.id %}';
可以把他放到 js 檔案中

2024-09-09 06:32 UTC, EricHsu521 commented
測試結果ok
1. 會出現複製頁面視窗，可以點選複製
![image](https://github.com/user-attachments/assets/2fff6405-d342-4d79-bf1c-1a3e2bc87dd0)

2. 網頁連結可以看到文章內容
![image](https://github.com/user-attachments/assets/c0df18c1-69dc-4aea-ab3f-d0ed3e00246c)

畫面方面後續再做調整

2024-09-09 06:34 UTC, EricHsu521 approved these changes

2024-09-09 11:17 UTC, jenjiunsu approved these changes
test ok

2024-09-12 03:24 UTC, KANG0918 approved these changes

2024-09-12 03:24 UTC, merged